plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.ksp)
    alias(libs.plugins.hilt)
    alias(libs.plugins.kotlinx.serialization)
}

val jdkVersion: JavaVersion = rootProject.extra["jdkVersion"] as JavaVersion
val sdkVersion: Int = rootProject.extra["sdkVersion"] as Int
val buildToolsVersionStr: String = rootProject.extra["buildToolsVersion"] as String

println("Using JDK $jdkVersion, SDK $sdkVersion")

android {
    namespace = "cn.edu.shmtu.terminal.android"
    compileSdk = sdkVersion
    buildToolsVersion = buildToolsVersionStr

    defaultConfig {
        applicationId = "cn.edu.shmtu.terminal.android"
        minSdk = 28
        targetSdk = sdkVersion
        versionCode = 1
        versionName = "1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }
    compileOptions {
        isCoreLibraryDesugaringEnabled = true
        sourceCompatibility = jdkVersion
        targetCompatibility = jdkVersion
    }
    buildFeatures {
        compose = true
    }

    // 将编译时生成的 git_contributors.json 加入 assets
    sourceSets.getByName("main") {
        assets.srcDir(File(buildDir, "generated/git_contributors/assets"))
    }
}

kotlin {
    compilerOptions {
        jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.fromTarget(jdkVersion.toString()))
    }
}

configurations.configureEach {
    resolutionStrategy.eachDependency {
        if (requested.group == "org.jetbrains.kotlin" && requested.name == "kotlin-metadata-jvm") {
            useVersion(libs.versions.kotlin.get())
            because("Hilt and Room processors must read Kotlin 2.4 metadata generated by this project")
        }
    }
}

dependencies {
    implementation(platform(libs.androidx.compose.bom))

    implementation(libs.androidx.activity.compose)
    implementation(libs.androidx.compose.material3)
    implementation(libs.androidx.compose.material3.adaptive.navigation.suite)
    implementation(libs.androidx.compose.material.icons.extended)
    implementation(libs.androidx.compose.ui)
    implementation(libs.androidx.compose.ui.graphics)
    implementation(libs.androidx.compose.ui.tooling.preview)
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.runtime.compose)

    implementation(libs.hilt.android)
    ksp(libs.hilt.android.compiler)
    implementation(libs.hilt.navigation.compose)

    implementation(libs.room.runtime)
    implementation(libs.room.ktx)
    ksp(libs.room.compiler)

    implementation(libs.navigation.compose)

    implementation(libs.kotlinx.coroutines.android)

    implementation(libs.koalaplot.core)

    implementation(libs.lifecycle.viewmodel.compose)

    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    ksp(libs.hilt.work.compiler)

    // OkHttp — BillRulesManager 从 GitHub 拉取规则文件
    implementation(libs.okhttp)

    // Coil — Compose 图像加载库 (About 页 GitHub 头像)
    implementation(libs.coil.compose)
    // NanoHTTPD - embedded Web server for remote bill browsing
    implementation(libs.nanohttpd)
    implementation(libs.nanohttpd.websocket)

    // ZXing — QR code generation and scanning for P2P
    implementation(libs.zxing.core)
    implementation(libs.zxing.android.embedded)

    // CameraX + ML Kit Barcode Scanning — P2P QR code scanning
    implementation(libs.camera.core)
    implementation(libs.camera.camera2)
    implementation(libs.camera.lifecycle)
    implementation(libs.camera.view)
    implementation(libs.mlkit.barcode.scanning)

    // kotlinx.serialization — P2P protocol type-safe serialization
    implementation(libs.kotlinx.serialization.json)

    testImplementation(libs.junit)
    androidTestImplementation(platform(libs.androidx.compose.bom))
    androidTestImplementation(libs.androidx.compose.ui.test.junit4)
    androidTestImplementation(libs.androidx.espresso.core)
    androidTestImplementation(libs.androidx.junit)

    debugImplementation(libs.androidx.compose.ui.test.manifest)
    debugImplementation(libs.androidx.compose.ui.tooling)

    implementation(libs.shmtu.cas.android)
    implementation(project(":shmtu_ocr"))
    coreLibraryDesugaring(libs.desugar.jdk.libs)
}

// ===== Git Contributors 构建任务 =====
// 在编译时检测是否为 git 仓库，提取所有提交者的 name + email，
// 写入 build/generated/git_contributors/assets/git_contributors.json，
// 供运行时 About 页面展示。
tasks.register("generateGitContributors") {
    group = "build"
    description = "Extract git contributors and write git_contributors.json"

    val outputDir = File(buildDir, "generated/git_contributors/assets")
    val outputFile = File(outputDir, "git_contributors.json")
    outputs.file(outputFile)

    doLast {
        outputDir.mkdirs()

        val isGitRepo = try {
            val proc = ProcessBuilder("git", "rev-parse", "--is-inside-work-tree")
                .directory(rootDir)
                .redirectErrorStream(true)
                .start()
            proc.inputStream.bufferedReader().readText().trim().equals("true", ignoreCase = true)
        } catch (_: Exception) {
            false
        }

        if (!isGitRepo) {
            outputFile.writeText("[]")
            logger.lifecycle("[GitContributors] Not a git repo, wrote empty array")
            return@doLast
        }

        val logOutput = try {
            val proc = ProcessBuilder("git", "log", "--format=%aN||%aE")
                .directory(rootDir)
                .redirectErrorStream(true)
                .start()
            proc.inputStream.bufferedReader().readText()
        } catch (_: Exception) {
            ""
        }

        if (logOutput.isBlank()) {
            outputFile.writeText("[]")
            logger.lifecycle("[GitContributors] Empty git log, wrote empty array")
            return@doLast
        }

        val seen = mutableSetOf<String>()
        val entries = mutableListOf<String>()

        for (line in logOutput.lines()) {
            val trimmed = line.trim()
            if (trimmed.isEmpty()) continue

            val parts = trimmed.split("||", limit = 2)
            if (parts.size != 2) continue

            val name = parts[0].trim()
            val email = parts[1].trim().lowercase()

            if (name.isEmpty() || email.isEmpty()) continue
            if (email in seen) continue
            seen.add(email)

            entries.add("""{"name":${jsonEscape(name)},"email":${jsonEscape(email)}}""")
        }

        val json = if (entries.isEmpty()) "[]" else "[${entries.joinToString(",")}]"
        outputFile.writeText(json)
        logger.lifecycle("[GitContributors] Wrote ${outputFile.absolutePath} (${entries.size} contributors)")
    }
}

fun jsonEscape(s: String): String {
    val sb = StringBuilder()
    sb.append('"')
    for (ch in s) {
        when (ch) {
            '"' -> sb.append("\\\"")
            '\\' -> sb.append("\\\\")
            '\n' -> sb.append("\\n")
            '\r' -> sb.append("\\r")
            '\t' -> sb.append("\\t")
            else -> {
                if (ch.code < 0x20) {
                    sb.append("\\u${ch.code.toString(16).padStart(4, '0')}")
                } else {
                    sb.append(ch)
                }
            }
        }
    }
    sb.append('"')
    return sb.toString()
}

tasks.matching { it.name.startsWith("merge") && it.name.endsWith("Assets") }.configureEach {
    dependsOn("generateGitContributors")
}
