plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.ksp)
    alias(libs.plugins.hilt)
    alias(libs.plugins.kotlinx.serialization)
}

val jdkVersion: JavaVersion = rootProject.extra["jdkVersion"] as JavaVersion
val sdkVersion: Int = rootProject.extra["sdkVersion"] as Int
val buildToolsVersionStr: String = rootProject.extra["buildToolsVersion"] as String

println("Using JDK $jdkVersion, SDK $sdkVersion")

/** 从 local.properties 或 Gradle -P 参数读取 OAuth 凭据 */
fun readProperty(key: String): String {
    if (project.hasProperty(key)) return project.property(key).toString()
    val f = rootProject.file("local.properties")
    if (!f.exists()) return ""
    var result = ""
    f.forEachLine { line ->
        val eq = line.indexOf('=')
        if (eq > 0 && line.substring(0, eq).trim() == key) {
            result = line.substring(eq + 1).trim()
        }
    }
    return result
}

android {
    namespace = "cn.edu.shmtu.terminal.android"
    compileSdk = sdkVersion
    buildToolsVersion = buildToolsVersionStr

    defaultConfig {
        applicationId = "cn.edu.shmtu.terminal.android"
        minSdk = 28
        targetSdk = sdkVersion
        versionCode = 1
        versionName = "1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"

        // OAuth 凭据（从 local.properties 或 Gradle -P 注入，空值 = 用户手动输入）
        buildConfigField("String", "CLOUD_GDRIVE_CLIENT_ID", "\"${readProperty("CLOUD_GDRIVE_CLIENT_ID")}\"")
        buildConfigField("String", "CLOUD_GDRIVE_CLIENT_SECRET", "\"${readProperty("CLOUD_GDRIVE_CLIENT_SECRET")}\"")
        buildConfigField("String", "CLOUD_ONEDRIVE_CLIENT_ID", "\"${readProperty("CLOUD_ONEDRIVE_CLIENT_ID")}\"")
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
        }
    }
    compileOptions {
        isCoreLibraryDesugaringEnabled = true
        sourceCompatibility = jdkVersion
        targetCompatibility = jdkVersion
    }
    buildFeatures {
        compose = true
        buildConfig = true
    }

    sourceSets.getByName("main") {
        assets.srcDir(File(buildDir, "generated/git_contributors/assets"))
    }
}

kotlin {
    compilerOptions {
        jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.fromTarget(jdkVersion.toString()))
    }
}

configurations.configureEach {
    resolutionStrategy.eachDependency {
        if (requested.group == "org.jetbrains.kotlin" && requested.name == "kotlin-metadata-jvm") {
            useVersion(libs.versions.kotlin.get())
            because("Hilt and Room processors must read Kotlin 2.4 metadata generated by this project")
        }
    }
}

dependencies {
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.activity.compose)
    implementation(libs.androidx.compose.material3)
    implementation(libs.androidx.compose.material3.adaptive.navigation.suite)
    implementation(libs.androidx.compose.material.icons.extended)
    implementation(libs.androidx.compose.ui)
    implementation(libs.androidx.compose.ui.graphics)
    implementation(libs.androidx.compose.ui.tooling.preview)
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.runtime.compose)

    implementation(libs.hilt.android)
    ksp(libs.hilt.android.compiler)
    implementation(libs.hilt.navigation.compose)

    implementation(libs.room.runtime)
    implementation(libs.room.ktx)
    ksp(libs.room.compiler)

    implementation(libs.navigation.compose)
    implementation(libs.kotlinx.coroutines.android)
    implementation(libs.koalaplot.core)
    implementation(libs.lifecycle.viewmodel.compose)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    ksp(libs.hilt.work.compiler)

    implementation(libs.okhttp)
    implementation(libs.coil.compose)
    implementation(libs.nanohttpd)
    implementation(libs.nanohttpd.websocket)
    implementation(libs.zxing.core)
    implementation(libs.zxing.android.embedded)
    implementation(libs.camera.core)
    implementation(libs.camera.camera2)
    implementation(libs.camera.lifecycle)
    implementation(libs.camera.view)
    implementation(libs.mlkit.barcode.scanning)

    implementation(libs.kotlinx.serialization.json)

    testImplementation(libs.junit)
    androidTestImplementation(platform(libs.androidx.compose.bom))
    androidTestImplementation(libs.androidx.compose.ui.test.junit4)
    androidTestImplementation(libs.androidx.espresso.core)
    androidTestImplementation(libs.androidx.junit)
    debugImplementation(libs.androidx.compose.ui.test.manifest)
    debugImplementation(libs.androidx.compose.ui.tooling)

    implementation(libs.shmtu.cas.android)
    implementation(project(":shmtu_ocr"))
    coreLibraryDesugaring(libs.desugar.jdk.libs)
}

// ===== Git Contributors 构建任务 =====
tasks.register("generateGitContributors") {
    group = "build"
    description = "Extract git contributors from this repo, submodules, and parent monorepo"
    val outputDir = File(buildDir, "generated/git_contributors/assets")
    val outputFile = File(outputDir, "git_contributors.json")
    outputs.file(outputFile)
    doLast {
        outputDir.mkdirs()
        val seen = mutableSetOf<String>()
        val entries = mutableListOf<String>()
        collectContributors(rootDir, seen, entries)
        collectFromSubmodules(rootDir, seen, entries)
        val json = if (entries.isEmpty()) "[]" else "[${entries.joinToString(",")}]"
        outputFile.writeText(json)
        logger.lifecycle("[GitContributors] Wrote ${outputFile.absolutePath} (${entries.size} contributors)")
    }
}

fun collectContributors(dir: File, seen: MutableSet<String>, entries: MutableList<String>) {
    val ignoredDomains = setOf("users.noreply.github.com", "example.com")
    val logOutput = runGit(dir, "log", "--format=%aN||%aE") ?: return
    for (line in logOutput.lines()) {
        val parts = line.trim().split("||", limit = 2)
        if (parts.size != 2) continue
        val name = parts[0].trim()
        val email = parts[1].trim().lowercase()
        if (name.isEmpty() || email.isEmpty() || email in seen) continue
        val domain = email.substringAfter("@", "")
        if (domain in ignoredDomains) continue
        seen.add(email)
        entries.add("""{"name":${jsonEscape(name)},"email":${jsonEscape(email)}}""")
    }
}

fun collectFromSubmodules(root: File, seen: MutableSet<String>, entries: MutableList<String>) {
    val statusOutput = runGit(root, "submodule", "status") ?: return
    for (line in statusOutput.lines()) {
        val parts = line.trim().splitWhitespace()
        if (parts.size < 2) continue
        val subPath = File(root, parts[1])
        if (File(subPath, ".git").exists() || File(subPath, ".git").isFile) {
            collectContributors(subPath, seen, entries)
            collectFromSubmodules(subPath, seen, entries)
        }
    }
}

fun runGit(dir: File, vararg args: String): String? = try {
    ProcessBuilder("git", *args).directory(dir).redirectErrorStream(true).start().inputStream.bufferedReader().readText()
} catch (_: Exception) { null }

fun String.splitWhitespace(): List<String> = this.trim().split(Regex("\\s+"))

fun jsonEscape(s: String): String {
    val sb = StringBuilder()
    sb.append('"')
    for (ch in s) {
        when (ch) {
            '"' -> sb.append("\\\"")
            '\\' -> sb.append("\\\\")
            '\n' -> sb.append("\\n")
            '\r' -> sb.append("\\r")
            '\t' -> sb.append("\\t")
            else -> if (ch.code < 0x20) sb.append("\\u${ch.code.toString(16).padStart(4, '0')}")
                     else sb.append(ch)
        }
    }
    sb.append('"')
    return sb.toString()
}

val genContributors = tasks.named("generateGitContributors")
tasks.matching { it.name.startsWith("merge") && it.name.endsWith("Assets") }.configureEach { dependsOn(genContributors) }
